# Generated by Django 3.1.2 on 2020-11-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='teammates',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
